import type { KanbanColumnData } from '../types';

export const initialKanbanData: KanbanColumnData[] = [
  {
    id: "todo",
    title: "To Do",
    cards: [
      {
        id: "1",
        title: "Design new user interface",
        description: "Create wireframes and mockups for the new dashboard",
        priority: "high",
        assignee: "Alice",
        tags: ["Design", "UI/UX"],
        done: false,
        isParent: true,
        parentId: null,
        subtasks: [
          { id: "s-1a", title: "Header layout", done: true, parentId: "1", isParent: false, subtasks: [], assignee: "Alice", priority: "medium" },
          { id: "s-1b", title: "Dashboard widgets", done: false, parentId: "1", isParent: false, subtasks: [], assignee: "Alice", priority: "medium" },
        ],
      },
      {
        id: "2",
        title: "Set up development environment",
        description: "Configure Docker containers and development tools",
        priority: "medium",
        assignee: "Bob",
        tags: ["DevOps", "Setup"],
        done: false,
        isParent: false,
        parentId: null,
        subtasks: [],
      },
      {
        id: "3",
        title: "Research user feedback",
        description: "Analyze user surveys and feedback from last quarter",
        priority: "low",
        assignee: "Carol",
        tags: ["Research", "Analytics"],
        done: false,
        isParent: false,
        parentId: null,
        subtasks: [],
      },
    ],
  },
  {
    id: "in-progress",
    title: "In Progress",
    cards: [
      {
        id: "4",
        title: "Implement authentication system",
        description: "Build secure login and registration functionality",
        priority: "high",
        assignee: "David",
        tags: ["Backend", "Security"],
        done: false,
        isParent: true,
        parentId: null,
        subtasks: [
          { id: "s-4a", title: "Login endpoint", done: true, assignee: "Dev A", priority: 'medium', tags: ["API"], dueDate: "Sep 25", parentId: "4", isParent: false, subtasks: [] },
          { id: "s-4b", title: "Register endpoint", done: false, assignee: "Dev B", priority: 'high', tags: ["API"], dueDate: "Sep 28", parentId: "4", isParent: true, subtasks: [
            { id: "s-4b-1", title: "Schema validation", done: false, assignee: "Dev C", priority: 'low', tags: ["Validation"], dueDate: "Sep 26", parentId: "s-4b", isParent: false, subtasks: [] },
          ] },
          { id: "s-4c", title: "JWT middleware", done: false, assignee: "Dev D", priority: 'urgent', tags: ["Security"], dueDate: "Oct 2", parentId: "4", isParent: false, subtasks: [] },
        ],
      },
      {
        id: "5",
        title: "Create API documentation",
        description: "Document all REST API endpoints with examples",
        priority: "medium",
        assignee: "Eve",
        tags: ["Documentation", "API"],
        done: false,
        isParent: false,
        parentId: null,
        subtasks: [],
      },
    ],
  },
  {
    id: "review",
    title: "Review",
    cards: [
      {
        id: "6",
        title: "Update user profile page",
        description: "Redesign profile page with new brand guidelines",
        priority: "medium",
        assignee: "Frank",
        tags: ["Frontend", "Design"],
        done: false,
        isParent: true,
        parentId: null,
        subtasks: [
          { id: "s-6a", title: "Avatar upload", done: false, parentId: "6", isParent: false, subtasks: [] },
        ],
      },
    ],
  },
  {
    id: "done",
    title: "Done",
    cards: [
      {
        id: "7",
        title: "Fix responsive layout issues",
        description: "Resolve mobile display problems on dashboard",
        priority: "high",
        assignee: "Grace",
        tags: ["Frontend", "Bug Fix"],
        done: true,
        isParent: false,
        parentId: null,
        subtasks: [],
      },
      {
        id: "8",
        title: "Optimize database queries",
        description: "Improve performance of user data retrieval",
        priority: "medium",
        assignee: "Henry",
        tags: ["Backend", "Performance"],
        done: true,
        isParent: false,
        parentId: null,
        subtasks: [],
      },
    ],
  },
];
